[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build:server"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
